### ISSUE TITLE
issues in installation

### ISSUE THREAD

**Issue by marcobrianza** [codemercs-com/node-cm-lw14udr-hid#1]
Hi I have tried to use the software but have faced some issues :

I can see the usb device:
 5304.130985] usb 1-1.3: new low-speed USB device number 8 using xhci_hcd
[ 5304.271790] usb 1-1.3: New USB device found, idVendor=07c0, idProduct=1501, bcdDevice=10.30
[ 5304.271820] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 5304.271841] usb 1-1.3: Product: IO-Warrior24
[ 5304.271859] usb 1-1.3: Manufacturer: Code Mercenaries
[ 5304.271876] usb 1-1.3: SerialNumber: 00006466
[ 5304.286894] iowarrior 1-1.3:1.0: IOWarrior product=0x1501, serial=00006466 interface=0 now attached to iowarrior0
[ 5304.297448] iowarrior 1-1.3:1.1: IOWarrior product=0x1501, serial=00006466 interface=1 now attached to iowarrior1

if I install node-hid as pi user I get errors so I installed it as root
sudo npm install -g node-hid

it works from command line

sudo hid-showdevices libusb
driverType: libusb
devices: [
  {
    vendorId: 1984,
    productId: 5377,
    path: '0001:0008:00',
    serialNumber: '00006466',
    manufacturer: 'Code Mercenaries',
    product: 'IO-Warrior24',
    release: 4144,
    interface: 0
  },
  {
    vendorId: 1984,
    productId: 5377,
    path: '0001:0008:01',
    serialNumber: '00006466',
    manufacturer: 'Code Mercenaries',
    product: 'IO-Warrior24',
    release: 4144,
    interface: 1
  }
]

I run node-red as root but get this error:

24 Jul 18:44:35 - [error] [send:e9f8bf2c.841e1] Error: Cannot find module 'node-hid'
Require stack:
- /root/.node-red/node_modules/node-cm-lw14udr-hid/lw14udr.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/lib/node_modules/node-red/lib/red.js
- /usr/lib/node_modules/node-red/red.js

any idea?

thank you and best regards
Marco

**Comment by codemercs-com** [comment]
On my test system I have install the 'node-hid' into ~/.node-red without root permissions without any errors.

cd ~/.node-red
npm install node-hid

After this I copy the node-cm-lw14udr-hid into ~/.node-red/node_modules and run 'node-red start'.

**Comment by marcobrianza** [comment]
hi, installing that way node-hid works, in fact at certain  point was already there but went the root way because I get this error: from the flow 

{"type":"error","code":8,"msg":"LED-Warrior14UDR not found with serial: 00006466"}

you n can see that the serial number matches.
the usb rules files are copied in the place

**Comment by codemercs-com** [comment]
Yes I ran into the same issue. If I install the node-hid global I get the missing serial number, but without its missing. And running node-red with root permission is not the best idea.

On my development machine I ran an older nodejs and node-red all without root permissions and works fine.
On the test device it fails.

I have open an issus-report on the node-hid github. Maybe they can help about this. It looks like a permission issue:
[https://github.com/node-hid/node-hid/issues/482](url)

**Comment by codemercs-com** [comment]
I have update the rules file to grant access for the iow24 to usb for group "pludgev".
On my old system this is not nessessary. Can you try the new rules with "normal" instance of node-red and node-hid (not globaly) on your machine?

**Comment by marcobrianza** [comment]
hi, yes this fixed the serial number error!
so I think it will work.

currently I'm out of office an accessed the device from remote.
I have the dali bus unpowered and get an error
{"type":"error","code":4,"msg":"Bus is faulty"}

good sign :-)

thank you

**Comment by marcobrianza** [comment]
Hi, I was back in office today and tested some functionality an confirm that it works correctly
